CC = cc
CFLAGS=-Wall -g

all: array truth exponents types values

array: array

truth: truth

types:

values:

exponents: 
	$(CC) $(CFLAGS) exponents.c -lm -o exponents 

clean:
	rm -rf array
	rm -rf truth
	rm -rf exponents
	rm -rf types
	rm -rf values
