CC = cc
CFLAGS=-Wall -g

all: array truth exponents types

array: array

truth: truth

types:
#	cc $(CFLAGS) types.c -o types

exponents: 
	$(CC) $(CFLAGS) exponents.c -lm -o exponents 

clean:
	rm -rf array
	rm -rf truth
	rm -rf exponents
	rm -rf types
